pipeline:
  build:
    image: quay.io/armswarm/golang:1.8-alpine
    environment:
      - CGO_ENABLED=0
    commands:
      - export OUTPUT_PATH=${PWD}
      - apk add --no-cache git
      - go get -d github.com/drone-plugins/drone-docker
      - cd $GOPATH/src/github.com/drone-plugins/drone-docker
      - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo
      - cp drone-docker ${OUTPUT_PATH}

  docker:
    image: armswarmdrone/docker
    repo: quay.io/armswarm/drone-docker
    tag: [ "17.05", "17", "latest" ]
    when:
      branch: master
      event: push

  slack:
    when:
      status: [ failure, success ]
