platform: linux/arm

workspace:
  base: /go
  path: src/github.com/armswarm/drone-docker

clone:
  git:
    image: armswarmdrone/git

pipeline:
  build:
    image: quay.io/armswarm/golang:1.8-alpine
    environment:
      - CGO_ENABLED=0
      - PACKAGE=github.com/drone-plugins/drone-docker
    commands:
      - echo "$${PACKAGE}"
      - go get -d "$${PACKAGE}"
      - go vet "$${PACKAGE}"
      - go test -cover -coverprofile=coverage.out "$${PACKAGE}"
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo -o "$${PACKAGE##*/}" "$${PACKAGE}"

  publish:
    image: armswarmdrone/docker
    repo: quay.io/armswarm/drone-docker
    tag: [ "17.05", "17", "latest" ]
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push

  notify:
    image: quay.io/armswarm/drone-slack
    secrets: [ slack_webhook, plugin_channel, plugin_template ]
    when:
      status: [ failure, success ]
